"""검증 엔진에서 사용하는 시점 고정 법정 기준.

값을 변경할 때는 KB.md의 공식 출처와 적용 기간을 먼저 갱신한다.
"""

STANDARD_YEAR = 2026

# KB.md: KB-MW-2026 / SRC-MINWAGE-2026
# 최저임금위원회: https://www.minimumwage.go.kr/minWage/policy/decisionMain.do
MINIMUM_WAGE_2026 = 10_320
MINIMUM_WAGE_SOURCE_ID = "SRC-MINWAGE-2026"

# KB.md: KB-WEEKLY-HOLIDAY-TIME / SRC-LSA-18
# 근로기준법 제18조제3항
WEEKLY_HOLIDAY_MIN_HOURS = 15.0
WEEKLY_HOLIDAY_SOURCE_ID = "SRC-LSA-18"

# KB.md: KB-BREAK-2026-07 / SRC-LSA-54-CURRENT
# 근로기준법 제54조. 큰 경계값부터 검사한다.
BREAK_RULES: tuple[tuple[float, int], ...] = (
    (8.0, 60),
    (4.0, 30),
)
BREAK_SOURCE_ID = "SRC-LSA-54-CURRENT"

# KB.md: KB-MINOR-WORKING-TIME / SRC-LSA-69, SRC-LSA-70
# 근로기준법 제69조·제70조 (2026-07-29 확인)
MINOR_AGE_LIMIT = 18
MINOR_DAILY_HOURS = 7.0
MINOR_WEEKLY_HOURS = 35.0
MINOR_EXT_DAILY_HOURS = 1.0
MINOR_EXT_WEEKLY_HOURS = 5.0
MINOR_NIGHT_START = "22:00"
MINOR_NIGHT_END = "06:00"
MINOR_SOURCE_ID = "SRC-LSA-69"
MINOR_NIGHT_SOURCE_ID = "SRC-LSA-70"

# KB.md: KB-SEVERANCE-ELIGIBILITY / SRC-ERBA-4, SRC-ERBA-8,
# SRC-MOEL-SEVERANCE-2025 (2026-07-30 확인)
# 금액은 계산하지 않고 계약상 예정 기간·주 소정근로시간 두 조건만 확인한다.
SEVERANCE_MIN_WEEKLY_HOURS = 15.0
SEVERANCE_CONTINUOUS_YEARS = 1
SEVERANCE_SOURCE_IDS = (
    "SRC-ERBA-4",
    "SRC-ERBA-8",
    "SRC-MOEL-SEVERANCE-2025",
)

# KB.md: KB-ANNUAL-LEAVE / SRC-LSA-60, SRC-LSA-11, SRC-LSA-18
ANNUAL_LEAVE_SOURCE_IDS = ("SRC-LSA-60", "SRC-LSA-11", "SRC-LSA-18")

# KB.md: KB-DISMISSAL-NOTICE / SRC-LSA-26
DISMISSAL_NOTICE_MIN_MONTHS = 3
DISMISSAL_NOTICE_SOURCE_ID = "SRC-LSA-26"

# KB.md: KB-PROBATION-MINIMUM-WAGE / SRC-MWA-5, SRC-MINWAGE-2026
PROBATION_DISCOUNT_RATE = 0.10
PROBATION_MIN_CONTRACT_YEARS = 1
PROBATION_MAX_MONTHS = 3
PROBATION_MINIMUM_WAGE_2026 = int(MINIMUM_WAGE_2026 * (1 - PROBATION_DISCOUNT_RATE))
PROBATION_SOURCE_IDS = (
    "SRC-MWA-5",
    "SRC-MWA-DECREE-3",
    "SRC-MINWAGE-2026",
)

# KB.md: KB-SOCIAL-INSURANCE
SOCIAL_INSURANCE_WEEKLY_HOURS = 15.0
SOCIAL_INSURANCE_MONTHLY_HOURS = 60.0
SOCIAL_INSURANCE_SOURCE_IDS = (
    "SRC-EASYLAW-EMPLOYMENT-INSURANCE",
    "SRC-NHIS-DECREE-9",
    "SRC-NPS-COVERAGE",
    "SRC-IACI-COVERAGE",
)
